///////////////////////////////////////////////////////////
//  User_Info.cs
//  Implementation of the Class User_Info
//  Generated by Enterprise Architect
//  Created on:      29-3月-2018 21:21:23
//  Original author: MungerLi
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class User_Info {

	/// <summary>
	/// 用户级别：一般用户，操作员，管理员
	/// </summary>
	private int Levels;
	/// <summary>
	/// 用户密码
	/// </summary>
	private int PassWord;
	/// <summary>
	/// 用户的状态
	/// </summary>
	private bool state;
	/// <summary>
	/// 用户的ID
	/// </summary>
	private int UserID;
	/// <summary>
	/// 用户姓名
	/// </summary>
	private int UserName;

	public User_Info(){

	}

	~User_Info(){

	}

	public int Leves(){

		return 0;
	}

	public int PassWord(){

		return 0;
	}

	public bool state(){

		return false;
	}

	public int UserID(){

		return 0;
	}

	public int UserName(){

		return 0;
	}

}//end User_Info