///////////////////////////////////////////////////////////
//  Bill.cs
//  Implementation of the Class Bill
//  Generated by Enterprise Architect
//  Created on:      08-11ÔÂ-2016 19:43:51
//  Original author: SweetyoYY
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Bill {

    //public int RemainCash { set; get; }
    public int RechargeMoney { set; get; }
    public int  ConsumeCash { set; get; }
    public int  AllCash { set; get; }
    public DateTime Date { set; get; }
    //public User m_User;

	public Bill(){

	}

	~Bill(){

	}

}//end Bill