///////////////////////////////////////////////////////////
//  Card.cs
//  Implementation of the Class Card
//  Generated by Enterprise Architect
//  Created on:      08-11ÔÂ-2016 19:43:52
//  Original author: SweetyoYY
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Entity
{
    public class Card
    {

        public int CardNo { set; get; }
        public string PassWord { set; get; }
        public int Money { set; get; }
        public string Type { set; get; }
        public string Notes { set; get; }
        public string Status { set; get; }
        public int StudentNo { set; get; }
        public string UserID { set; get; }
        public Entity.User m_User;

        public Card()
        {

        }

        ~Card()
        {

        }

        /// 
        /// <param name="CardNo"></param>
        //public void PK_Card(int CardNo)
        //{

        //}
    }

}//end Card