///////////////////////////////////////////////////////////
//  line.cs
//  Implementation of the Class line
//  Generated by Enterprise Architect
//  Created on:      08-11ÔÂ-2016 19:43:53
//  Original author: SweetyoYY
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Entity
{
    public class line
    {

        public int CardNo { set; get; }
        public int StudentNo { set; get; }
        public string StudentName { set; get; }
        public DateTime LoginDate { set; get; }
        public TimeSpan  LoginTime { set; get; }
        public DateTime OffDate { set; get; }
        public TimeSpan  OffTime { set; get; }
        public int ConsumeTime { set; get; }
        public float ConsumeMoney { set; get; }
        public float Money { set; get; }
        public string Status { set; get; }
        public string Computer { set; get; }
        public string sex { set; get; }
        public string cardType { set; get; }
        public Entity.Card m_Card;

        public line()
        {

        }

        ~line()
        {

        }

        /// 
        /// <param name="CardNo"></param>
        /// <param name="UserID"></param>
        public void PK_line(int CardNo, string UserID)
        {

        }
    }
}//end line