///////////////////////////////////////////////////////////
//  User.cs
//  Implementation of the Class User
//  Generated by Enterprise Architect
//  Created on:      08-11ÔÂ-2016 19:43:54
//  Original author: SweetyoYY
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Entity
{
    public class User
    {

        public string UserID { set; get; }
        public string UserName { set; get; }
        public string PassWord { set; get; }
        public string Level { set; get; }
        public string Head { set; get; }

        public User()
        {

        }

        ~User()
        {

        }

        /// 
        /// <param name="UserID"></param>
        public void PK_User(string UserID)
        {

        }

    }//end User
}