///////////////////////////////////////////////////////////
//  WorkLog.cs
//  Implementation of the Class WorkLog
//  Generated by Enterprise Architect
//  Created on:      08-11ÔÂ-2016 19:43:54
//  Original author: SweetyoYY
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Entity
{
    public class WorkLog
    {

        public string UserID { set; get; }
        public string Level { set; get; }
        public DateTime LogDate { set; get; }
        public TimeSpan  LogTime { set; get; }
        public DateTime OffDate { set; get; }
        public TimeSpan  OffTime { set; get; }
        public string Computer { set; get; }
        public string Status { set; get; }
       // public Entity.User m_User { set; get; }

        public WorkLog()
        {

        }

        ~WorkLog()
        {

        }

        /// 
        /// <param name="UserID"></param>
        public void PK_WorkLog(string UserID)
        {

        }

    }//end WorkLog
}